- type: homeassistant
- type: trusted_networks
  trusted_networks:
    - 192.168.4.0/8
  trusted_users:
    192.168.4.0: 7989d710709249ee98e8f0cc8a3f38f3
  allow_bypass_login: true
  # Note that bypass_login only works if one user is authorized
